### ISSUE TITLE
I had to run drive_auth()

### ISSUE THREAD

**Issue by eeholmes** [MargaretSiple-NOAA/googledrive-to-rmd-example#2]
```
googledrive::drive_auth()
```
before kniting the first time from the command line

**Comment by MargaretSiple-NOAA** [comment]
Ooh, I didn't try this from the command line. Though i would expect that the `source(here::here("get_files_from_gdrive.R"))` line in the `MainDocument.Rmd` file would have done that for you 🤔. Would it suffice for me to just add a note to the README?

**Comment by eeholmes** [comment]
You have to run that one time (only) from the R command line. Otherwise it
will throw an authentication error because the R script is being called the
first time in non-interactive mode (in an Rmd)

You wouldn't have noticed since the first time you ran `drive_auth()` it was in interactive mode as you wore developing.

Might have been ages ago that you first ran `drive_auth()`. I think it is being stored somewhere in a keychain...
